version: '3'
services:
  bot:
    build: ./bot
    environment:
      - DATABASE_URL=postgresql://user:password@db/rss
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./bot:/app
    depends_on:
      - db
    command: python bot.py

  monitoring:
    build: ./monitoring
    environment:
      - DATABASE_URL=postgresql://user:password@db/rss
    volumes:
      - ./monitoring:/app
    depends_on:
      - db
    command: python monitor.py

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rss
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network: